version: '3.9'
services:
  r1:
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: r1
    volumes:
    - ./scripts:/shared_data
    environment:
      CONTAINER_NAME: r1
      CUSTO_r1_r2_net: '6'
      CUSTO_r1_r4_net: '8'
      CUSTO_r1_r5_net: '3'
    networks:
      r1_r2_net:
        ipv4_address: 10.10.1.2
      r1_r4_net:
        ipv4_address: 10.10.2.2
      r1_r5_net:
        ipv4_address: 10.10.3.2
      r1_hosts_net:
        ipv4_address: 192.168.6.2
    cap_add:
    - NET_ADMIN
  r1_h1:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r1_h1
    volumes:
    - ./scripts:/scripts
    networks:
      r1_hosts_net:
        ipv4_address: 192.168.6.3
    cap_add:
    - NET_ADMIN
  r1_h2:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r1_h2
    volumes:
    - ./scripts:/scripts
    networks:
      r1_hosts_net:
        ipv4_address: 192.168.6.4
    cap_add:
    - NET_ADMIN
  r2:
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: r2
    volumes:
    - ./scripts:/shared_data
    environment:
      CONTAINER_NAME: r2
      CUSTO_r1_r2_net: '6'
      CUSTO_r2_r3_net: '10'
    networks:
      r1_r2_net:
        ipv4_address: 10.10.1.3
      r2_r3_net:
        ipv4_address: 10.10.4.2
      r2_hosts_net:
        ipv4_address: 192.168.7.2
    cap_add:
    - NET_ADMIN
  r2_h1:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r2_h1
    volumes:
    - ./scripts:/scripts
    networks:
      r2_hosts_net:
        ipv4_address: 192.168.7.3
    cap_add:
    - NET_ADMIN
  r2_h2:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r2_h2
    volumes:
    - ./scripts:/scripts
    networks:
      r2_hosts_net:
        ipv4_address: 192.168.7.4
    cap_add:
    - NET_ADMIN
  r3:
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: r3
    volumes:
    - ./scripts:/shared_data
    environment:
      CONTAINER_NAME: r3
      CUSTO_r2_r3_net: '10'
    networks:
      r2_r3_net:
        ipv4_address: 10.10.4.3
      r3_hosts_net:
        ipv4_address: 192.168.8.2
    cap_add:
    - NET_ADMIN
  r3_h1:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r3_h1
    volumes:
    - ./scripts:/scripts
    networks:
      r3_hosts_net:
        ipv4_address: 192.168.8.3
    cap_add:
    - NET_ADMIN
  r3_h2:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r3_h2
    volumes:
    - ./scripts:/scripts
    networks:
      r3_hosts_net:
        ipv4_address: 192.168.8.4
    cap_add:
    - NET_ADMIN
  r4:
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: r4
    volumes:
    - ./scripts:/shared_data
    environment:
      CONTAINER_NAME: r4
      CUSTO_r1_r4_net: '8'
    networks:
      r1_r4_net:
        ipv4_address: 10.10.2.3
      r4_hosts_net:
        ipv4_address: 192.168.9.2
    cap_add:
    - NET_ADMIN
  r4_h1:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r4_h1
    volumes:
    - ./scripts:/scripts
    networks:
      r4_hosts_net:
        ipv4_address: 192.168.9.3
    cap_add:
    - NET_ADMIN
  r4_h2:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r4_h2
    volumes:
    - ./scripts:/scripts
    networks:
      r4_hosts_net:
        ipv4_address: 192.168.9.4
    cap_add:
    - NET_ADMIN
  r5:
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: r5
    volumes:
    - ./scripts:/shared_data
    environment:
      CONTAINER_NAME: r5
      CUSTO_r1_r5_net: '3'
    networks:
      r1_r5_net:
        ipv4_address: 10.10.3.3
      r5_hosts_net:
        ipv4_address: 192.168.10.2
    cap_add:
    - NET_ADMIN
  r5_h1:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r5_h1
    volumes:
    - ./scripts:/scripts
    networks:
      r5_hosts_net:
        ipv4_address: 192.168.10.3
    cap_add:
    - NET_ADMIN
  r5_h2:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: r5_h2
    volumes:
    - ./scripts:/scripts
    networks:
      r5_hosts_net:
        ipv4_address: 192.168.10.4
    cap_add:
    - NET_ADMIN
networks:
  r1_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.6.0/24
  r2_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.7.0/24
  r3_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.8.0/24
  r4_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.9.0/24
  r5_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.10.0/24
  r1_r2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.1.0/24
  r1_r4_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.2.0/24
  r1_r5_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.3.0/24
  r2_r3_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.4.0/24
